name: Publish @kiva/ssirius-standalone
on:
  push:
    branches:
      - 'main'

jobs:
  build_and_publish_standalone:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@kiva'
      - name: Install and publish @kiva/ssirius-standalone
        run: |
          cd ./standalone
          npm ci
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.SSIRIUS_STANDALONE_TOKEN }}
      